CREATE DATABASE [DigitMusic]
GO
USE [DigitMusic]
GO
CREATE TABLE [Artist]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(200) NOT NULL UNIQUE
)
GO
CREATE TABLE [Album]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Artist_Id INT NOT NULL,
    Title NVARCHAR(255) NOT NULL
)
GO
ALTER TABLE [Album] WITH CHECK ADD CONSTRAINT [Album_Artist_FK] FOREIGN KEY ([Artist_Id]) REFERENCES [Artist]([Id])
GO
CREATE TABLE [Playlist]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(200) NOT NULL
)
GO
CREATE TABLE [PlaylistTrack]
(
    Playlist_Id INT NOT NULL,
    Track_Id INT NOT NULL,
    PRIMARY KEY (Playlist_Id, Track_Id)
)
GO
ALTER TABLE [PlaylistTrack] WITH CHECK ADD CONSTRAINT [PlaylistTrack_Playlist_FK] FOREIGN KEY ([Playlist_Id]) REFERENCES [Playlist]([Id]) ON DELETE CASCADE
GO
CREATE TABLE [MediaType]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(200) NOT NULL UNIQUE
)
GO
CREATE TABLE [Genre]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(200) NOT NULL UNIQUE
)
GO
CREATE TABLE [Track]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(200) NOT NULL,
    Album_Id INT NOT NULL,
    MediaType_Id INT NOT NULL,
    Genre_Id INT NOT NULL,
    Duration TIME NOT NULL,
    Bytes INT NOT NULL,
    Price SMALLMONEY NOT NULL DEFAULT(5),
    Location TEXT NOT NULL DEFAULT('./')
)
GO
ALTER TABLE [Track] WITH CHECK ADD CONSTRAINT [Track_Album_FK] FOREIGN KEY ([Album_Id]) REFERENCES [Album]([Id])
GO
ALTER TABLE [PlaylistTrack] WITH CHECK ADD CONSTRAINT [PlaylistTrack_Track_FK] FOREIGN KEY ([Track_Id]) REFERENCES [Track]([Id]) ON DELETE CASCADE
GO
ALTER TABLE [Track] WITH CHECK ADD CONSTRAINT [Track_MediaType_FK] FOREIGN KEY ([MediaType_Id]) REFERENCES [MediaType]([Id])
GO
ALTER TABLE [Track] WITH CHECK ADD CONSTRAINT [Track_Genre_FK] FOREIGN KEY ([Genre_Id]) REFERENCES [Genre]([Id])
GO
CREATE TABLE [InvoiceTrack]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Invoice_Id INT NOT NULL,
    Track_Id INT NOT NULL,
    Quantity INT NOT NULL DEFAULT(1)
)
GO
ALTER TABLE [InvoiceTrack] WITH CHECK ADD CONSTRAINT [InvoiceTrack_Track_FK] FOREIGN KEY ([Track_Id]) REFERENCES [Track]([Id])
GO
CREATE TABLE [Invoice]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Customer_Id INT NOT NULL,
    InvoiceDate DATETIME NOT NULL DEFAULT(GETDATE()),
    BillingAddress NVARCHAR(256) NOT NULL,
    BillingCity NVARCHAR(256) NOT NULL,
    BillingState NVARCHAR(256) NOT NULL,
    BillingCountry VARCHAR(128) NOT NULL,
    BillingPostalCode VARCHAR(10) NOT NULL
)
GO
ALTER TABLE [InvoiceTrack] WITH CHECK ADD CONSTRAINT [InvoiceTrack_Invoice_FK] FOREIGN KEY ([Invoice_Id]) REFERENCES [Invoice]([Id]) ON DELETE CASCADE
GO
CREATE TABLE [Employee]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    JobPosition NVARCHAR(100) NOT NULL,
    ReportsTo_Id INT,
    BirthDate DATETIME NOT NULL,
    HireDate DATETIME NOT NULL DEFAULT(GETDATE()),
    Address NVARCHAR(256) NOT NULL,
    City NVARCHAR(256) NOT NULL,
    State NVARCHAR(256) NOT NULL,
    Country VARCHAR(128) NOT NULL,
    PostalCode VARCHAR(10) NOT NULL,
    Phone VARCHAR(15) NOT NULL UNIQUE,
    Email NVARCHAR(320) NOT NULL UNIQUE
)
GO
ALTER TABLE [Employee] WITH CHECK ADD CONSTRAINT [Employee_Employee_FK] FOREIGN KEY ([ReportsTo_Id]) REFERENCES [Employee]([Id])
GO
CREATE TABLE [Customer]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NameOrFirm NVARCHAR(300) NOT NULL,
    Address NVARCHAR(256) NOT NULL,
    City NVARCHAR(256) NOT NULL,
    State NVARCHAR(256) NOT NULL,
    Country VARCHAR(128) NOT NULL,
    PostalCode VARCHAR(10) NOT NULL,
    Phone VARCHAR(15) NOT NULL UNIQUE,
    Email NVARCHAR(320) NOT NULL UNIQUE,
    EmployeeSupport_Id INT NOT NULL
)
GO
ALTER TABLE [Customer] WITH CHECK ADD CONSTRAINT [Customer_Employee_FK] FOREIGN KEY ([EmployeeSupport_Id]) REFERENCES [Employee]([Id])
GO
ALTER TABLE [Invoice] WITH CHECK ADD CONSTRAINT [Invoice_Customer_FK] FOREIGN KEY ([Customer_Id]) REFERENCES [Customer]([Id]);